import type { Room } from '../types';

export const rooms = [
  {
    id: 'A-101',
    name: 'A-101',
    building: 'A',
    floor: 1,
    capacity: 4,
    image: null,
    equipment: { projector: false, whiteboard: true, highSpecPc: false, ac: true },
  },
  {
    id: 'A-204',
    name: 'A-204',
    building: 'A',
    floor: 2,
    capacity: 8,
    image: null,
    equipment: { projector: true, whiteboard: true, highSpecPc: false, ac: true },
  },
  {
    id: 'A-315',
    name: 'A-315',
    building: 'A',
    floor: 3,
    capacity: 12,
    image: null,
    equipment: { projector: true, whiteboard: false, highSpecPc: true, ac: true },
  },
  {
    id: 'A-402',
    name: 'A-402',
    building: 'A',
    floor: 4,
    capacity: 18,
    image: null,
    equipment: { projector: false, whiteboard: false, highSpecPc: false, ac: false },
  },
  {
    id: 'B-103',
    name: 'B-103',
    building: 'B',
    floor: 1,
    capacity: 2,
    image: null,
    equipment: { projector: false, whiteboard: true, highSpecPc: false, ac: true },
  },
  {
    id: 'B-208',
    name: 'B-208',
    building: 'B',
    floor: 2,
    capacity: 6,
    image: null,
    equipment: { projector: true, whiteboard: false, highSpecPc: false, ac: true },
  },
  {
    id: 'B-307',
    name: 'B-307',
    building: 'B',
    floor: 3,
    capacity: 10,
    image: null,
    equipment: { projector: false, whiteboard: true, highSpecPc: true, ac: true },
  },
  {
    id: 'B-411',
    name: 'B-411',
    building: 'B',
    floor: 4,
    capacity: 20,
    image: null,
    equipment: { projector: true, whiteboard: true, highSpecPc: true, ac: false },
  },
  {
    id: 'C-102',
    name: 'C-102',
    building: 'C',
    floor: 1,
    capacity: 5,
    image: null,
    equipment: { projector: false, whiteboard: false, highSpecPc: false, ac: true },
  },
  {
    id: 'C-216',
    name: 'C-216',
    building: 'C',
    floor: 2,
    capacity: 9,
    image: null,
    equipment: { projector: true, whiteboard: true, highSpecPc: false, ac: true },
  },
  {
    id: 'C-308',
    name: 'C-308',
    building: 'C',
    floor: 3,
    capacity: 14,
    image: null,
    equipment: { projector: false, whiteboard: true, highSpecPc: true, ac: false },
  },
  {
    id: 'C-420',
    name: 'C-420',
    building: 'C',
    floor: 4,
    capacity: 16,
    image: null,
    equipment: { projector: true, whiteboard: false, highSpecPc: false, ac: true },
  },
  {
    id: 'V-105',
    name: 'V-105',
    building: 'V',
    floor: 1,
    capacity: 3,
    image: null,
    equipment: { projector: false, whiteboard: true, highSpecPc: false, ac: false },
  },
  {
    id: 'V-212',
    name: 'V-212',
    building: 'V',
    floor: 2,
    capacity: 7,
    image: null,
    equipment: { projector: true, whiteboard: false, highSpecPc: true, ac: true },
  },
  {
    id: 'V-309',
    name: 'V-309',
    building: 'V',
    floor: 3,
    capacity: 11,
    image: null,
    equipment: { projector: false, whiteboard: true, highSpecPc: false, ac: true },
  },
  {
    id: 'V-415',
    name: 'V-415',
    building: 'V',
    floor: 4,
    capacity: 19,
    image: null,
    equipment: { projector: true, whiteboard: true, highSpecPc: true, ac: true },
  },
] satisfies Room[];
